# Generated by Django 5.2.12 on 2026-03-23 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("idea_one_liner", models.CharField(max_length=255)),
                ("raw_description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("INTERVIEWING", "Interviewing"),
                            ("RESEARCHING", "Researching"),
                            ("SCORED", "Scored"),
                            ("DECIDED", "Decided"),
                        ],
                        default="DRAFT",
                        max_length=32,
                    ),
                ),
                (
                    "current_decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BUILD_NOW", "Build now"),
                            ("RUN_VALIDATION_FIRST", "Run validation first"),
                            ("NARROW_NICHE", "Narrow niche"),
                            ("PIVOT", "Pivot"),
                            ("KILL", "Kill"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "latest_research_snapshot",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "latest_structured_model_snapshot",
                    models.JSONField(blank=True, default=dict),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StartupProfileSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("summary", models.TextField(blank=True)),
                ("icp", models.TextField(blank=True)),
                ("problem_statement", models.TextField(blank=True)),
                ("alternatives", models.JSONField(blank=True, default=list)),
                ("value_prop", models.TextField(blank=True)),
                ("monetization_hypothesis", models.TextField(blank=True)),
                ("acquisition_hypothesis", models.TextField(blank=True)),
                ("founder_edge", models.TextField(blank=True)),
                ("constraints", models.TextField(blank=True)),
                ("structured_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
                "unique_together": {("project", "version")},
            },
        ),
        migrations.CreateModel(
            name="Assumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=64)),
                ("statement", models.TextField()),
                ("confidence", models.FloatField(default=0.5)),
                (
                    "evidence_status",
                    models.CharField(default="UNVERIFIED", max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assumptions",
                        to="projects.project",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assumptions",
                        to="projects.startupprofilesnapshot",
                    ),
                ),
            ],
        ),
    ]
