# Generated by Django 5.2.12 on 2026-03-23 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="QUEUED",
                        max_length=32,
                    ),
                ),
                ("provider", models.CharField(default="mock", max_length=64)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("summary_json", models.JSONField(blank=True, default=dict)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_runs",
                        to="projects.project",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_runs",
                        to="projects.startupprofilesnapshot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Competitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField(blank=True)),
                ("positioning", models.TextField(blank=True)),
                ("target_customer", models.TextField(blank=True)),
                ("pricing_summary", models.TextField(blank=True)),
                ("strengths", models.JSONField(blank=True, default=list)),
                ("weaknesses", models.JSONField(blank=True, default=list)),
                (
                    "research_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitors",
                        to="research.researchrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResearchSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_name", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField()),
                ("published_at", models.DateField(blank=True, null=True)),
                ("domain", models.CharField(blank=True, max_length=255)),
                ("source_type", models.CharField(default="web", max_length=64)),
                ("credibility_score", models.FloatField(default=0.5)),
                (
                    "research_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="research.researchrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvidenceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("COMPETITOR", "Competitor"),
                            ("MARKET", "Market signal"),
                            ("PAIN", "Pain signal"),
                            ("PRICING", "Pricing"),
                            ("SEARCH", "Search demand"),
                            ("RISK", "Risk"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("snippet", models.TextField()),
                ("extracted_claim", models.TextField()),
                ("relevance_score", models.FloatField(default=0.5)),
                ("confidence_score", models.FloatField(default=0.5)),
                ("citation_json", models.JSONField(blank=True, default=dict)),
                (
                    "research_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_items",
                        to="research.researchrun",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_items",
                        to="research.researchsource",
                    ),
                ),
            ],
        ),
    ]
