# Generated by Django 5.2.12 on 2026-03-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researchrun",
            name="provider",
            field=models.CharField(default="live_web", max_length=64),
        ),
    ]
