# Generated by Django 5.2.12 on 2026-03-23 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(default="ACTIVE", max_length=32)),
                (
                    "current_phase",
                    models.CharField(
                        choices=[
                            ("CLARIFY", "Clarify the idea"),
                            ("ICP", "Identify target user"),
                            ("PAIN", "Pain intensity"),
                            ("ALTERNATIVES", "Existing alternatives"),
                            ("MONETIZATION", "Willingness to pay"),
                            ("ACQUISITION", "Distribution"),
                            ("EDGE", "Founder edge"),
                            ("REVIEW", "Assumption review"),
                            ("COMPLETE", "Complete"),
                        ],
                        default="CLARIFY",
                        max_length=32,
                    ),
                ),
                ("completion_percent", models.PositiveIntegerField(default=0)),
                ("phase_confidence_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_sessions",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InterviewMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SYSTEM", "System"),
                            ("ASSISTANT", "Assistant"),
                            ("USER", "User"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("CLARIFY", "Clarify the idea"),
                            ("ICP", "Identify target user"),
                            ("PAIN", "Pain intensity"),
                            ("ALTERNATIVES", "Existing alternatives"),
                            ("MONETIZATION", "Willingness to pay"),
                            ("ACQUISITION", "Distribution"),
                            ("EDGE", "Founder edge"),
                            ("REVIEW", "Assumption review"),
                            ("COMPLETE", "Complete"),
                        ],
                        max_length=32,
                    ),
                ),
                ("content", models.TextField()),
                ("extracted_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="interviews.interviewsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
