# Generated by Django 5.2.12 on 2026-03-23 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("scoring", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("BUILD_NOW", "Build now"),
                            ("RUN_VALIDATION_FIRST", "Run validation first"),
                            ("NARROW_NICHE", "Narrow niche"),
                            ("PIVOT", "Pivot"),
                            ("KILL", "Kill"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reasoning", models.TextField()),
                ("strengths_json", models.JSONField(default=list)),
                ("weaknesses_json", models.JSONField(default=list)),
                ("blockers_json", models.JSONField(default=list)),
                ("conditions_json", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="projects.project",
                    ),
                ),
                (
                    "scoring_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="scoring.scoringresult",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="projects.startupprofilesnapshot",
                    ),
                ),
            ],
        ),
    ]
