# Generated by Django 5.2.12 on 2026-03-23 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoringResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_score", models.FloatField()),
                ("dimension_scores_json", models.JSONField(default=dict)),
                ("weights_json", models.JSONField(default=dict)),
                ("risk_flags_json", models.JSONField(default=list)),
                ("rationale_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoring_results",
                        to="projects.project",
                    ),
                ),
                (
                    "research_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoring_results",
                        to="research.researchrun",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoring_results",
                        to="projects.startupprofilesnapshot",
                    ),
                ),
            ],
        ),
    ]
