# Generated by Django 5.2.12 on 2026-03-23 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("INTERVIEW_SCRIPT", "Customer interview script"),
                            ("OUTREACH_DM", "Cold outreach DM"),
                            ("OUTREACH_EMAIL", "Cold outreach email"),
                            ("LANDING_PAGE", "Landing page copy"),
                            ("MVP_SCOPE", "MVP scope"),
                            ("VALIDATION_PLAN", "7-day validation plan"),
                            ("CHECKLIST", "Experiment checklist"),
                            ("METRICS", "Success metrics"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("metadata_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="projects.project",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="projects.startupprofilesnapshot",
                    ),
                ),
            ],
        ),
    ]
